50 add dark mode
abozanona/luca pull request #62
Opened 2022-06-02 12:31 UTC by Mahmoud-Skafi

2022-06-03 15:51 UTC, Mahmoud-Skafi commented
@abozanona please chack again!

2022-06-04 07:04 UTC, abozanona commented
There's an issue in the design where chat background doesn't show on party

<img width="545" alt="image" src="https://user-images.githubusercontent.com/12738028/171988654-cfff0223-24c8-4673-a2c2-e7f3110517b7.png">

2022-06-04 07:09 UTC, abozanona requested changes
There's an issue in the design where chat background doesn't show on party

Everything else looks find.

@Mahmoud-Skafi Please fix so we cam merge.

<img width="545" alt="image" src="https://user-images.githubusercontent.com/12738028/171988654-cfff0223-24c8-4673-a2c2-e7f3110517b7.png">

2022-06-04 09:23 UTC, abozanona approved these changes

2022-06-04 09:23 UTC, merged